name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World1"
          echo "Testing second Line"
      - name: Print goodby
        run: echo "Done - bye!"
